### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by mglidden** [pburtchaell/react-input#6]
Getting this error: `Uncaught TypeError: props.className is not a function(…)` on fields.js, line 13. Just cloned from master.

**Comment by pburtchaell** [comment]
Thanks for the heads up @mglidden. I'll take a look.

**Comment by pburtchaell** [comment]
This is resolved. Let me know if you have any further issues! Thanks. 😄

**Comment by alandickinson** [comment]
I'm seeing this same error for line 33 in fields.js. `Uncaught TypeError: props.className is not a function`. Just installed via npm `npm install react-input`.

**Comment by Allend13** [comment]
@alandickinson same for me :(

**Comment by pburtchaell** [comment]
@alandickinson @Allend13 @mglidden Can you install `react-input@4.1.2` and confirm if the issue is resolved in this release? Tests pass for version 4.1.2.

**Comment by mglidden** [comment]
Running the examples in the repo works for me
